defaults:
  - _self_
  - daft_target: gmm_2d_target
  - override hydra/sweeper: list
  - override hydra/launcher: joblib

exp_name: gmm_2d_target_non_amortized_projection

hydra:
    mode: MULTIRUN
    launcher:
        n_jobs: 2
    sweeper:
      grid_params:
#        daft_target.algorithm.more.component_kl_bound: 0.01, 0.001, 0.005, 0.0001, 0.0005
        daft_target.seed: 1001, 1002, 1003, 1004, 1005
