defaults:
  - _self_
  - daft_target: star_2d_target
  - override hydra/sweeper: list
  - override hydra/launcher: joblib

exp_name: 2d_star_target_DAFT

hydra:
    mode: MULTIRUN
    launcher:
        n_jobs: 2
    sweeper:
      grid_params:
#        daft_target.algorithm.more.component_kl_bound: 0.01, 0.001, 0.005, 0.0001, 0.0005
        daft_target.seed: 1001
