wandb_version: 1

n_epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 8
n_context:
  desc: null
  value: 640
fc_layer_size:
  desc: null
  value: 16
init_lr:
  desc: null
  value: 0.01
initialization_type:
  desc: null
  value: orthogonal
weight_decay:
  desc: null
  value: 1.0e-05
_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709281882.638016
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.7.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
