defaults:
  - _self_
  - target: gmm_target
  - schema: no_projection
  - seed: a
#  - override hydra/sweeper: list

#exp_name: 4GMM_4GMM
exp_name: 4GMM_4GMM_algorithm_1

hydra:
  sweeper:
    params:
      target: gmm_target
      schema: projection_4gmm
#      schema: no_projection
      seed:  a
