defaults:
  - _self_
  - target: gmm_target
  - schema: no_projection
  - seed: a
  - override hydra/sweeper: list

#exp_name: gmm_algo_basic
#exp_name: gmm_algo_kl
#exp_name: gmm_algo_direct
exp_name: gmm_algo_stl

hydra:
  sweeper:
    grid_params:
      schema: no_projection
#      schema: projection_4gmm
      seed: a,b, c,d,e,f
