defaults:
  - _self_
  - target: bmm_target
  - schema: no_projection
  - seed: a
  - override hydra/sweeper: list

#exp_name: 5BMM_algo_basic
#exp_name: 5BMM_algo_kl
#exp_name: 5BMM_algo_w2
exp_name: 5BMM_algo_direct
#exp_name: 5BMM_algo_stl

hydra:
  sweeper:
    grid_params:
      target: bmm_target
      schema: no_projection
#      schema: no_projection
      seed:  a, b, c, e, f, h

