defaults:
  - _self_
  - seed: seed_a
  - target: gmm_target
  - schema: no_projection

hydra:
  sweeper:
    params:
      seed: seed_a, seed_b, seed_c
      target: gmm_target
      schema: no_projection, projection