defaults:
  - _self_
  - target: funnel_target
  - schema: no_projection
  - seed: a
  - override hydra/sweeper: list

#exp_name: 10d_funnel_algo_basic
#exp_name: 10d_funnel_algo+
#exp_name: 10d_funnel_algo_kl
#exp_name: 10d_funnel_algo_direct
exp_name: 10d_funnel_algo_stl

hydra:
  sweeper:
    grid_params:
#      schema: projection_10d_funnel
#      target.model_name: ["toy_task_model_2", "toy_task_model_3", "toy_task_model_1"]
      seed: b, c
#      schema.alpha: [2]
#    list_params:
#      schema.eps_mean: [0.1]
#      schema.eps_cov: [0.]
