defaults:
  - _self_
  - target: bmm_target
  - schema: no_projection
  - seed: a
#  - override hydra/sweeper: list

exp_name: 5BMM_10GMM

hydra:
  sweeper:
    params:
      target: bmm_target
      schema: no_projection
      seed:  b, c, d, e, f