defaults:
  - _self_
  - target: bmm_target
  - schema: projection
  - seed: a
#  - override hydra/sweeper: list

exp_name: BMM

#seed: 1001
job_type: 5bmm_10gmm

hydra:
  sweeper:
    params:
      target: bmm_target
      schema: no_projection
      seed: b