defaults:
  - _self_
  - seed: seed_a
  - target: bmm_target
  - schema: no_projection

hydra:
  sweeper:
    params:
      seed: seed_a
      target: bmm_target
      schema: no_projection, projection