n_epochs: 1500
batch_size: 128
n_context: 1280
n_components: 10
n_samples: 10
fc_layer_size: 256
#init_lr: 0.0005
gate_lr: 0.0001
gaussian_lr: 0.0001

model_name: "toy_task_2d_model"
target_name: "bmm"
dim: 2
initialization_type: "xavier"