n_epochs: 1500
batch_size: 128
n_context: 1280
n_components: 10
n_samples: 10
gate_lr: 0.0001
gaussian_lr: 0.0001

model_name: "toy_task_model_1"
dim: 2
initialization_type: "xavier"

target_name: "bmm"
target_components: 5
