n_epochs: 400
batch_size: 96
n_context: 960
n_components: 4
num_gate_layer: 5
num_component_layer: 7
n_samples: 10
gate_lr: 0.01
gaussian_lr: 0.01

model_name: "toy_task_model_2"
dim: 2
initialization_type: "xavier"

target_name: "gmm"
target_components: 4
