n_epochs: 400
batch_size: 64
n_context: 640
n_components: 4
n_samples: 10
gate_lr: 0.001
gaussian_lr: 0.001

model_name: "toy_task_model_1"
dim: 2
initialization_type: "xavier"

target_name: "gmm"
target_components: 4
