defaults:
  - _self_
#  - target: 30_gmm_target
  - target: 10_gmm_2d_target_adaption
  - schema: no_projection
  - seed: a
  - override hydra/sweeper: list

#exp_name: algo_basic
#exp_name: algo_kl
#exp_name: algo_direct
#exp_name: algo_stl
#exp_name: random_init_30_components_no_gate_projection
#exp_name: init_10_components_no_adaptation
exp_name: gate_strategy_sweeper_ctx_2d_mdl_init1_max15_tgt_max10
#exp_name: init_1_components_single_context


hydra:
    mode: MULTIRUN
    sweeper:
      grid_params:
        target.gate_strategy:
          - 2
          - 3.1
          - 3.2
          - 3.3
          - 3.4
          - 3.5
#        seed: [a, b, c]
#      list_params:
#        target.n_samples: [5, 10]
#        target.batch_size: [128, 64]