defaults:
  - _self_
  - gmm_target: 10_gmm_2d_target
  - override hydra/sweeper: list
  - override hydra/launcher: joblib

exp_name: gmm_2d_target_amortized_projection_30k


hydra:
    mode: MULTIRUN
    launcher:
        n_jobs: 10
    sweeper:
      grid_params:
#        gmm_target.model_config.num_gate_layer: 2, 3, 4, 5
#        gmm_target.model_config.num_component_layer: 3, 4, 5
#        gmm_target.model_config.num_neuron_component_layer: 64, 128, 256
        gmm_target.training_config.gate_lr: 1e-3, 1e-2
#        gmm_target.projection.alpha: [5, 10, 50, 75]
        gmm_target.seed: [1001, 1002, 1003, 1004, 1005]
#      list_params:
#        gmm_target.projection.eps_mean: [0.01, 0.01, 0.001, 0.005, 0.0005, 0.0001]
#        gmm_target.projection.eps_cov: [0.001, 0.0001, 0.0001, 0.0005, 0.0001, 0.0001]
#        gmm_target.training_config.n_epochs: [10000, 5000, 1000]
#        gmm_target.training_config.batch_size: [640, 128, 64]
