defaults:
  - _self_
  - funnel_target: funnel_target
  - override hydra/sweeper: list
  - override hydra/launcher: joblib

exp_name: funnel_target_amortized


hydra:
    mode: MULTIRUN
    launcher:
        n_jobs: 10
    sweeper:
      grid_params:
#        funnel_target.model_config.num_gate_layer: 5
#        funnel_target.model_config.num_component_layer: 5, 6, 7
#        funnel_target.model_config.num_neuron_component_layer: 128, 256
        funnel_target.seed: [1001, 1002, 1003]
#      list_params:
#        funnel_target.projection.eps_mean: [0.1, 0.1, 0.1, 0.01, 0.01, 0.001, 0.005, 0.0005, 0.0001]
#        funnel_target.projection.eps_cov: [0.01, 0.001, 0.0001, 0.001, 0.0001, 0.0001, 0.0005, 0.0001, 0.0001]