defaults:
  - _self_
#  - target: 30_gmm_target
  - target: 10_gmm_2d_target_adaption
  - schema: no_projection
  - seed: a
  - override hydra/sweeper: list
  - override hydra/launcher: submitit_slurm

#exp_name: algo_basic
#exp_name: algo_kl
#exp_name: algo_direct
#exp_name: algo_stl
#exp_name: random_init_30_components_no_gate_projection
#exp_name: init_10_components_no_adaptation
exp_name: init_1_max_10_components_2d_context
#exp_name: init_1_components_single_context


hydra:
  # multirun
  sweep:
    dir: /home/kit/anthropomatik/ic7094/wandb/${now:%Y-%m-%d_%H-%M-%S}
  # single run
  run:
    dir: /home/kit/anthropomatik/ic7094/wandb/${now:%Y-%m-%d_%H-%M-%S}

  mode: MULTIRUN

  # SLURM
  launcher:
    submitit_folder: /home/kit/anthropomatik/ic7094/wandb/%j
#    partition: "dev_gpu_4"
#    timeout_min: 30  # in minutes
    partition: "gpu_8"
    timeout_min: 180 # in minutes
    gres: gpu:2
    mem_per_gpu: 94000  # in MB
    additional_parameters:
      cpus-per-task: 4  # maybe more?

  sweeper:
    grid_params:
      seed: [a, b, c]
    #    list_params:
    #      target.num_gate_layer: [3,4,5,4,5,6 ]
    #      target.num_component_layer: [5,5,5,6,6,6]