defaults:
  - _self_
  - star_target: star_2d_target
  - override hydra/sweeper: list
  - override hydra/launcher: joblib


exp_name: star_2d_target_amortized_projection


hydra:
    mode: MULTIRUN
    launcher:
        n_jobs: 10
    sweeper:
      grid_params:
        star_target.projection.alpha: [5, 10, 50, 75]
        star_target.seed: [1001, 1002, 1003, 1004, 1005]
#      list_params:
#        star_target.projection.eps_mean: [0.01, 0.01, 0.001, 0.005, 0.0005, 0.0001]
#        star_target.projection.eps_cov: [0.001, 0.0001, 0.0001, 0.0005, 0.0001, 0.0001]
