defaults:
  - _self_
  - target: 30_gmm_target
  - schema: no_projection
  - seed: a
#  - override hydra/sweeper: list

#exp_name: algo_basic
exp_name: algo_kl
#exp_name: algo_direct
#exp_name: algo_stl

#hydra:
#  sweeper:
#    grid_params:
#      target.
#    list_params:
#      target.num_gate_layer: [3,4,5,4,5,6 ]
#      target.num_component_layer: [5,5,5,6,6,6]


