---
name: "toy_task"

path: "/home/luyao/amortized_vi_trpl/result/"
repetitions: 1


params:
    n_epochs: 150
    batch_size: 64
    n_context: 640
    n_components: 4
    n_samples: 10
    fc_layer_size: 256
    init_lr: 0.01
    eps_mean: 0.1
    eps_cov: 0.5
    alpha: 2

    project: True

    model_name: "toy_task_model"
    initialization_type: "xavier"


