n_epochs: 6000
batch_size: 128
n_context: 1280
max_components: 10
init_components: 1
num_gate_layer: 3
num_component_layer: 5
n_samples: 5
gate_lr: 0.0001
gaussian_lr: 0.001

model_name: "toy_task_model_3"
dim: 2
context_dim: 2
random_init: False
initialization_type: "xavier"

target_name: "gmm"
target_components: 10
