n_epochs: 1000
batch_size: 128
n_context: 1280
n_components: 8
num_gate_layer: 5   #2
num_component_layer: 7  #5
n_samples: 10
gate_lr: 0.0001
gaussian_lr: 0.0001

model_name: "toy_task_model_2"
dim: 10
initialization_type: "xavier"

target_name: "funnel"
target_components: 10


