# config for experiment:  compare daft and amortized vips

# training config
n_epochs: 300
batch_size: 32
n_context: 320
num_gate_layer: 3
num_component_layer: 5
n_samples: 5
gate_lr: 0.001
gaussian_lr: 0.01
gate_strategy: 3.3
history_size: 150

# model config
model_name: "toy_task_model_3"
dim: 2
context_dim: 2
random_init: True
initialization_type: "xavier"
max_components: 10
init_components: 10

# target config
target_name: "star"
target_components: 5
